In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.DataFrame({'Text':['people watch campus','campus watch campus','people write comment','comment write comment'],'output':[1,1,0,0]})

In [3]:
df

Text  output
0    people watch campus       1
1    campus watch campus       1
2   people write comment       0
3  comment write comment       0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [5]:
bow = cv.fit_transform(df['Text'])

In [6]:
#vocab
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campus': 0, 'write': 4, 'comment': 1}


In [7]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [8]:
cv.transform(['campus watch and write comment of campus']).toarray()

array([[2, 1, 0, 1, 1]], dtype=int64)

In [9]:
#N-GRAMS: group of words in n gram 

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [11]:
bow = cv.fit_transform(df['Text'])

In [12]:
print(cv.vocabulary_)

{'people watch': 2, 'watch campus': 4, 'campus watch': 0, 'people write': 3, 'write comment': 5, 'comment write': 1}


In [13]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())


[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]
[[0 0 0 1 0 1]]
[[0 1 0 0 0 1]]


In [14]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [15]:
bow = cv.fit_transform(df['Text'])

In [16]:
print(cv.vocabulary_)

{'people watch campus': 2, 'campus watch campus': 0, 'people write comment': 3, 'comment write comment': 1}


In [17]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[0 0 1 0]]
[[1 0 0 0]]
[[0 0 0 1]]
[[0 1 0 0]]


In [18]:
#tf-idf

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['Text']).toarray()

array([[0.57735027, 0.        , 0.57735027, 0.57735027, 0.        ],
       [0.89442719, 0.        , 0.        , 0.4472136 , 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.        , 0.89442719, 0.        , 0.        , 0.4472136 ]])

In [24]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.51082562 1.51082562 1.51082562 1.51082562 1.51082562]
['campus' 'comment' 'people' 'watch' 'write']
